#!/usr/bin/env bash
# vim: ts=2 sw=2 sts=2 et :

Ell="$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )"

doc() {
  (cd $Ell
  pdoc3 -o $Ell/docs -f --html $Ell/keys0.py
  mv $Ell/docs/keys0.html $Ell/docs/index.html)
}

alias gp="git commit -am saving; git push"
alias keys="python3.9 $Ell/keys0.py "
