#!/usr/bin/env gawk -f

/^---/ {        $0="\n\033[01;36m"$0"\033[0m" }
/FAIL/ { bad++; $NF="\033[31m"$NF"\033[0m" }
/PASS/ {        $NF="\033[32m"$NF"\033[0m" }
       { print  $0                 }
END    { exit bad!=0 } 

